# A Python program is read by a **parser**. Input to the parser is a stream of
# tokens, generated by the **tokenizer**. 

# The end of a logical line is represented by the token NEWLINE, statements
# cannot cross logical line boundaries except where NEWLINE is allowed by the
# syntax. A logical line is constructed from one or more **physical lines**
# by following the explicit or implicit line **joining** rules.

# Two or more physical lines may be joined into logical lines using backslash
# characters (`\`), as follows

year = 2018
month = 3
day = 14
hour = 12
minute = 6
second = 47

if 1900 < year < 2100 and 1 <= month <= 12 and \
    1 <= day <= 31 and 0 <= hour < 24 and \
    0 <= minute < 60 and 0 <= second < 60 :
        print("{}-{}-{} {}:{}:{}".format(
            year,
            str(month).zfill(2),
            str(day).zfill(2),
            str(hour).zfill(2),
            str(minute).zfill(2),
            str(second).zfill(2)
        ))

# A line ending in a backslash cannot carry a comment. A backslash does not continue
# a comment. Expressions in parentheses, square brackets or curly braces can be split
# over more than one physical line without using backslashes, for example

month_names = [
    "January", "February", "March", "April",
    "May", "June", "July", "August",
    "September", "October", "November", "December"
]

# Leading whitespace (space or tab) at the beginning of a logical line is used to
# compute the indention level of the line, which in turn is used to determine the
# grouping of statements.

# Indention is rejected as inconsistent if a source file mixes tabs and spaces in
# a way that makes the meaning dependent on the worth of a tab in spaces, a
# `TabError` is raised in that case.